### ISSUE TITLE
No module named 'helpers'

### ISSUE THREAD

**Issue by mingcc** [staranjeet/github-trending-cli#1]
i run githubtrending after pip install github-trending , but i get  No module named 'helpers'   issue ,  how can i solve this problem?

**Comment by taranjeet** [comment]
which python version are you using? OS?

**Comment by mingcc** [comment]
python 3.5  on Windows 7

**Comment by taranjeet** [comment]
I have updated the package. Try updating on your machine.
If your are facing issues in updating, just uninstall the package via
`pip uninstall github-trending`
and then re-install it via
`pip install github-trending`

Hope it fixes the issue.

**Comment by mingcc** [comment]
now it raises    SyntaxError: except Exception,e:

**Comment by taranjeet** [comment]
This issue is arising because you are using Python 3.5 and I have developed this package using Python 2.7. I will fix this issue soon.

**Comment by taranjeet** [comment]
@mingcc : Updated the package. version 1.0.2
Update me if there any issues comes in.

**Comment by mingcc** [comment]
it worked now

**Comment by taranjeet** [comment]
Thanks for pointing out the issue. This package now supports Python 3 as well. Very soon trending developers list will also be displayed.
@mingcc

**Comment by taranjeet** [comment]
@mingcc : Now the support for developers is also available.
Options available are

```
-r, --repo                                         # for repositories
-d, --dev                                         # for developers
```
